### PR TITLE
Adding Callback function to build method for updates

### PR DESCRIPTION
**Pull request by Jon-Salmon**
For a project I'm working on I required a callback function to be run whenever the shortcut values changed (to update the UI to reflect the change). I'm creating this PR as it may be useful to others.

An optional parameter `callback` is added to the `build` method. This is called (as long as it is a function) whenever the commands are updated or reset.

### CODE REVIEW

**Comment by piroor** [comment]
Thank you for a feedback!

A callback function for the "build()" method seems confusable, because it already returns a promise and it will be used with another callback like:

```javascript
ShortcutCustomizeUI.build(() => { /* do something on updated */ }).then(list => {
  // do something after created
  document.getElementById('shortcuts').appendChild(list);
});
```

Moreover, the method may receive more extra parameters in the future. Thus, instead of adding a callback function, I think a custom event looks better. It will work as:

```javascript
ShortcutCustomizeUI.build().then(list => {
  document.getElementById('shortcuts').appendChild(list);
  list.addEventListener('ShortcutChanged', event => {
    // console.log(event.target, event.detail.key)
    ...
  });
});
```

Custom events can be dispatched like:

```javascript
const event = new CustomEvent('ShortcutChanged', {
  detail: {
    key: keyField.value
  }
});
item.dispatcheEvent(event);
```

How about this design?

**Comment by Jon-Salmon** [comment]
This does look a much cleaner way of doing it and works fine for my purposes. I've updated the PR to reflect the changes

**Comment by Jon-Salmon** [comment]
I set the event up to return the changed command's id as well as the full new shortcut, do you think that's a suitable level of info?

**Comment by piroor** [comment]
Thanks a lot!

> I set the event up to return the changed command's id as well as the full new shortcut, do you think that's a suitable level of info?

Sorry I have no idea about this point, because I originally developed this library just for a static options page and didn't require this feature on my usecase. If you need something more information for the event, please send new PRs freely.

Anyway, I think that the current design (event.target == list) is better than my draft, because the user of the library should not know details of internal implementation of this library itself.

**Pull request merged**
